//! # KernelLens FFI Layer
//!
//! This crate provides the Foreign Function Interface (FFI) for
//! exposing kernel_core functionality to Flutter/Dart via flutter_rust_bridge.

#![allow(unexpected_cfgs)] // For frb_expand warning in macros

/// The main API exposed to Flutter.
pub mod api;

#[allow(unsafe_code)]
#[allow(missing_docs)]
mod frb_generated; /* AUTO GENERATED BY flutter_rust_bridge_codegen */
