// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:kernel_lens_app/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Analyze a boot image file and return header information.
Future<BootImageHeader> getBootInfo({required String path}) =>
    RustLib.instance.api.crateApiGetBootInfo(path: path);

/// Analyze a kernel with real-time progress updates.
Stream<ProgressUpdate> startAnalysis({required String inputPath}) =>
    RustLib.instance.api.crateApiStartAnalysis(inputPath: inputPath);

/// Detect compression format of a file.
Future<CompressionFormat> detectCompression({required String path}) =>
    RustLib.instance.api.crateApiDetectCompression(path: path);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AnalysisSession>>
abstract class AnalysisSession implements RustOpaqueInterface {
  Uint8List get elfBytes;

  AnalysisSummary get summary;

  set elfBytes(Uint8List elfBytes);

  set summary(AnalysisSummary summary);

  /// Get the total count of symbols after filtering (for pagination).
  Future<BigInt> countFiltered({required String filter});

  /// Read a chunk of the kernel for hex viewing.
  ///
  /// Alignment: This method aligns the offset and length to 16 bytes
  /// to simplify UI rendering (one row = 16 bytes).
  Future<HexChunk> getHexChunk({
    required BigInt offset,
    required BigInt length,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Start a new analysis session.
  static Future<AnalysisSession> newInstance({required String inputPath}) =>
      RustLib.instance.api.crateApiAnalysisSessionNew(inputPath: inputPath);

  /// Query symbols using server-side filtering and sorting.
  ///
  /// This is a "Zero-Copy" operation effectively, as we only return
  /// the small subset of data requested by the UI view.
  Future<List<FrbKernelSymbol>> querySymbols({
    required String filter,
    required SortColumn sortBy,
    required bool ascending,
    required BigInt page,
    required BigInt pageSize,
  });
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BootImageHeader>>
abstract class BootImageHeader implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CompressionFormat>>
abstract class CompressionFormat implements RustOpaqueInterface {}

/// Lightweight summary of the analysis result.
class AnalysisSummary {
  /// Size of decomrpessed kernel bytes.
  final BigInt kernelSize;

  /// CPU architecture (e.g., AArch64).
  final String arch;

  /// Base address of the kernel code.
  final BigInt kernelBase;

  /// Total number of symbols found.
  final BigInt symbolCount;

  const AnalysisSummary({
    required this.kernelSize,
    required this.arch,
    required this.kernelBase,
    required this.symbolCount,
  });

  @override
  int get hashCode =>
      kernelSize.hashCode ^
      arch.hashCode ^
      kernelBase.hashCode ^
      symbolCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalysisSummary &&
          runtimeType == other.runtimeType &&
          kernelSize == other.kernelSize &&
          arch == other.arch &&
          kernelBase == other.kernelBase &&
          symbolCount == other.symbolCount;
}

/// A Flutter-friendly version of KernelSymbol.
class FrbKernelSymbol {
  /// Symbol virtual address.
  final BigInt addr;

  /// Symbol name.
  final String name;

  /// Symbol type string (e.g., "T", "t", "D").
  final String stype;

  const FrbKernelSymbol({
    required this.addr,
    required this.name,
    required this.stype,
  });

  @override
  int get hashCode => addr.hashCode ^ name.hashCode ^ stype.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKernelSymbol &&
          runtimeType == other.runtimeType &&
          addr == other.addr &&
          name == other.name &&
          stype == other.stype;
}

/// A chunk of hex data for the viewer.
class HexChunk {
  /// Raw byte content.
  final Uint8List content;

  /// Starting offset in the file/memory.
  final BigInt offset;

  /// Total size of the underlying data (for scrollbar calculation).
  final BigInt totalSize;

  const HexChunk({
    required this.content,
    required this.offset,
    required this.totalSize,
  });

  @override
  int get hashCode => content.hashCode ^ offset.hashCode ^ totalSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HexChunk &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          offset == other.offset &&
          totalSize == other.totalSize;
}

/// Real-time progress update for the analysis pipeline.
class ProgressUpdate {
  /// Current analytical step description.
  final String step;

  /// Progress value from 0.0 to 1.0.
  final double progress;

  /// Partial analysis metadata (if available).
  final AnalysisSummary? summary;

  /// The final session object (only set in the last update).
  final AnalysisSession? session;

  const ProgressUpdate({
    required this.step,
    required this.progress,
    this.summary,
    this.session,
  });

  @override
  int get hashCode =>
      step.hashCode ^ progress.hashCode ^ summary.hashCode ^ session.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProgressUpdate &&
          runtimeType == other.runtimeType &&
          step == other.step &&
          progress == other.progress &&
          summary == other.summary &&
          session == other.session;
}

/// Column to sort by.
enum SortColumn {
  /// Sort by virtual address.
  address,

  /// Sort by symbol name.
  name,

  /// Sort by symbol type.
  type,
}
