// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:kernel_lens_app/src/rust/frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Analyze a boot image file and return header information.
Future<BootImageHeader> getBootInfo({required String path}) =>
    RustLib.instance.api.crateApiGetBootInfo(path: path);

/// Full analysis pipeline: parse -> decompress -> analyze -> build ELF.
Future<AnalysisResult> analyzeKernel({required String inputPath}) =>
    RustLib.instance.api.crateApiAnalyzeKernel(inputPath: inputPath);

/// Detect compression format of a file.
Future<CompressionFormat> detectCompression({required String path}) =>
    RustLib.instance.api.crateApiDetectCompression(path: path);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BootImageHeader>>
abstract class BootImageHeader implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CompressionFormat>>
abstract class CompressionFormat implements RustOpaqueInterface {}

/// Complete analysis result for Flutter.
class AnalysisResult {
  /// Size of decompressed kernel.
  final BigInt kernelSize;

  /// Detected architecture.
  final String arch;

  /// Kernel base address.
  final BigInt kernelBase;

  /// Number of recovered symbols.
  final BigInt symbolCount;

  /// All recovered symbols.
  final List<FrbKernelSymbol> symbols;

  /// Generated ELF file bytes.
  final Uint8List elfBytes;

  const AnalysisResult({
    required this.kernelSize,
    required this.arch,
    required this.kernelBase,
    required this.symbolCount,
    required this.symbols,
    required this.elfBytes,
  });

  @override
  int get hashCode =>
      kernelSize.hashCode ^
      arch.hashCode ^
      kernelBase.hashCode ^
      symbolCount.hashCode ^
      symbols.hashCode ^
      elfBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalysisResult &&
          runtimeType == other.runtimeType &&
          kernelSize == other.kernelSize &&
          arch == other.arch &&
          kernelBase == other.kernelBase &&
          symbolCount == other.symbolCount &&
          symbols == other.symbols &&
          elfBytes == other.elfBytes;
}

/// A Flutter-friendly version of KernelSymbol.
class FrbKernelSymbol {
  final BigInt addr;
  final String name;
  final String stype;

  const FrbKernelSymbol({
    required this.addr,
    required this.name,
    required this.stype,
  });

  @override
  int get hashCode => addr.hashCode ^ name.hashCode ^ stype.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbKernelSymbol &&
          runtimeType == other.runtimeType &&
          addr == other.addr &&
          name == other.name &&
          stype == other.stype;
}
