// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'package:kernel_lens_app/src/rust/api.dart';
import 'dart:async';
import 'dart:convert';
import 'package:kernel_lens_app/src/rust/frb_generated.dart';
import 'package:kernel_lens_app/src/rust/frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -891585390;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'kernel_ffi',
        ioDirectory: '../crates/kernel_ffi/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Uint8List crateApiAnalysisSessionAutoAccessorGetElfBytes({
    required AnalysisSession that,
  });

  AnalysisSummary crateApiAnalysisSessionAutoAccessorGetSummary({
    required AnalysisSession that,
  });

  void crateApiAnalysisSessionAutoAccessorSetElfBytes({
    required AnalysisSession that,
    required Uint8List elfBytes,
  });

  void crateApiAnalysisSessionAutoAccessorSetSummary({
    required AnalysisSession that,
    required AnalysisSummary summary,
  });

  Future<BigInt> crateApiAnalysisSessionCountFiltered({
    required AnalysisSession that,
    required String filter,
  });

  Future<HexChunk> crateApiAnalysisSessionGetHexChunk({
    required AnalysisSession that,
    required BigInt offset,
    required BigInt length,
  });

  Future<AnalysisSession> crateApiAnalysisSessionNew({
    required String inputPath,
  });

  Future<List<FrbKernelSymbol>> crateApiAnalysisSessionQuerySymbols({
    required AnalysisSession that,
    required String filter,
    required SortColumn sortBy,
    required bool ascending,
    required BigInt page,
    required BigInt pageSize,
  });

  Future<CompressionFormat> crateApiDetectCompression({required String path});

  Future<BootImageHeader> crateApiGetBootInfo({required String path});

  Future<void> crateApiInitApp();

  Stream<ProgressUpdate> crateApiStartAnalysis({required String inputPath});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AnalysisSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AnalysisSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AnalysisSessionPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_BootImageHeader;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_BootImageHeader;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BootImageHeaderPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CompressionFormat;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CompressionFormat;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_CompressionFormatPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Uint8List crateApiAnalysisSessionAutoAccessorGetElfBytes({
    required AnalysisSession that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAnalysisSessionAutoAccessorGetElfBytesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalysisSessionAutoAccessorGetElfBytesConstMeta =>
      const TaskConstMeta(
        debugName: "AnalysisSession_auto_accessor_get_elf_bytes",
        argNames: ["that"],
      );

  @override
  AnalysisSummary crateApiAnalysisSessionAutoAccessorGetSummary({
    required AnalysisSession that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_analysis_summary,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAnalysisSessionAutoAccessorGetSummaryConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalysisSessionAutoAccessorGetSummaryConstMeta =>
      const TaskConstMeta(
        debugName: "AnalysisSession_auto_accessor_get_summary",
        argNames: ["that"],
      );

  @override
  void crateApiAnalysisSessionAutoAccessorSetElfBytes({
    required AnalysisSession that,
    required Uint8List elfBytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_strict(elfBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAnalysisSessionAutoAccessorSetElfBytesConstMeta,
        argValues: [that, elfBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalysisSessionAutoAccessorSetElfBytesConstMeta =>
      const TaskConstMeta(
        debugName: "AnalysisSession_auto_accessor_set_elf_bytes",
        argNames: ["that", "elfBytes"],
      );

  @override
  void crateApiAnalysisSessionAutoAccessorSetSummary({
    required AnalysisSession that,
    required AnalysisSummary summary,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
            that,
            serializer,
          );
          sse_encode_analysis_summary(summary, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAnalysisSessionAutoAccessorSetSummaryConstMeta,
        argValues: [that, summary],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalysisSessionAutoAccessorSetSummaryConstMeta =>
      const TaskConstMeta(
        debugName: "AnalysisSession_auto_accessor_set_summary",
        argNames: ["that", "summary"],
      );

  @override
  Future<BigInt> crateApiAnalysisSessionCountFiltered({
    required AnalysisSession that,
    required String filter,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
            that,
            serializer,
          );
          sse_encode_String(filter, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAnalysisSessionCountFilteredConstMeta,
        argValues: [that, filter],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalysisSessionCountFilteredConstMeta =>
      const TaskConstMeta(
        debugName: "AnalysisSession_count_filtered",
        argNames: ["that", "filter"],
      );

  @override
  Future<HexChunk> crateApiAnalysisSessionGetHexChunk({
    required AnalysisSession that,
    required BigInt offset,
    required BigInt length,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
            that,
            serializer,
          );
          sse_encode_usize(offset, serializer);
          sse_encode_usize(length, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_hex_chunk,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAnalysisSessionGetHexChunkConstMeta,
        argValues: [that, offset, length],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalysisSessionGetHexChunkConstMeta =>
      const TaskConstMeta(
        debugName: "AnalysisSession_get_hex_chunk",
        argNames: ["that", "offset", "length"],
      );

  @override
  Future<AnalysisSession> crateApiAnalysisSessionNew({
    required String inputPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAnalysisSessionNewConstMeta,
        argValues: [inputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalysisSessionNewConstMeta => const TaskConstMeta(
    debugName: "AnalysisSession_new",
    argNames: ["inputPath"],
  );

  @override
  Future<List<FrbKernelSymbol>> crateApiAnalysisSessionQuerySymbols({
    required AnalysisSession that,
    required String filter,
    required SortColumn sortBy,
    required bool ascending,
    required BigInt page,
    required BigInt pageSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
            that,
            serializer,
          );
          sse_encode_String(filter, serializer);
          sse_encode_sort_column(sortBy, serializer);
          sse_encode_bool(ascending, serializer);
          sse_encode_usize(page, serializer);
          sse_encode_usize(pageSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_frb_kernel_symbol,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAnalysisSessionQuerySymbolsConstMeta,
        argValues: [that, filter, sortBy, ascending, page, pageSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalysisSessionQuerySymbolsConstMeta =>
      const TaskConstMeta(
        debugName: "AnalysisSession_query_symbols",
        argNames: ["that", "filter", "sortBy", "ascending", "page", "pageSize"],
      );

  @override
  Future<CompressionFormat> crateApiDetectCompression({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCompressionFormat,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDetectCompressionConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDetectCompressionConstMeta =>
      const TaskConstMeta(debugName: "detect_compression", argNames: ["path"]);

  @override
  Future<BootImageHeader> crateApiGetBootInfo({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBootImageHeader,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetBootInfoConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetBootInfoConstMeta =>
      const TaskConstMeta(debugName: "get_boot_info", argNames: ["path"]);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Stream<ProgressUpdate> crateApiStartAnalysis({required String inputPath}) {
    final sink = RustStreamSink<ProgressUpdate>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(inputPath, serializer);
            sse_encode_StreamSink_progress_update_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 12,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiStartAnalysisConstMeta,
          argValues: [inputPath, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiStartAnalysisConstMeta => const TaskConstMeta(
    debugName: "start_analysis",
    argNames: ["inputPath", "sink"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_AnalysisSession => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_AnalysisSession => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_BootImageHeader => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBootImageHeader;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_BootImageHeader => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBootImageHeader;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CompressionFormat => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCompressionFormat;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CompressionFormat => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCompressionFormat;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  AnalysisSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnalysisSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BootImageHeader
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBootImageHeader(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BootImageHeaderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CompressionFormat
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCompressionFormat(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CompressionFormatImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AnalysisSession
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnalysisSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AnalysisSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnalysisSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  AnalysisSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnalysisSessionImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BootImageHeader
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBootImageHeader(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BootImageHeaderImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  CompressionFormat
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCompressionFormat(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CompressionFormatImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<ProgressUpdate> dco_decode_StreamSink_progress_update_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AnalysisSummary dco_decode_analysis_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AnalysisSummary(
      kernelSize: dco_decode_usize(arr[0]),
      arch: dco_decode_String(arr[1]),
      kernelBase: dco_decode_u_64(arr[2]),
      symbolCount: dco_decode_usize(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AnalysisSession
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
      raw,
    );
  }

  @protected
  AnalysisSummary dco_decode_box_autoadd_analysis_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_analysis_summary(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FrbKernelSymbol dco_decode_frb_kernel_symbol(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FrbKernelSymbol(
      addr: dco_decode_u_64(arr[0]),
      name: dco_decode_String(arr[1]),
      stype: dco_decode_String(arr[2]),
    );
  }

  @protected
  HexChunk dco_decode_hex_chunk(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HexChunk(
      content: dco_decode_list_prim_u_8_strict(arr[0]),
      offset: dco_decode_u_64(arr[1]),
      totalSize: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<FrbKernelSymbol> dco_decode_list_frb_kernel_symbol(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_frb_kernel_symbol).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  AnalysisSession?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
            raw,
          );
  }

  @protected
  AnalysisSummary? dco_decode_opt_box_autoadd_analysis_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_analysis_summary(raw);
  }

  @protected
  ProgressUpdate dco_decode_progress_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ProgressUpdate(
      step: dco_decode_String(arr[0]),
      progress: dco_decode_f_32(arr[1]),
      summary: dco_decode_opt_box_autoadd_analysis_summary(arr[2]),
      session:
          dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
            arr[3],
          ),
    );
  }

  @protected
  SortColumn dco_decode_sort_column(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SortColumn.values[raw as int];
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  AnalysisSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AnalysisSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  BootImageHeader
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBootImageHeader(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BootImageHeaderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CompressionFormat
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCompressionFormat(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CompressionFormatImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AnalysisSession
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AnalysisSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AnalysisSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AnalysisSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  AnalysisSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return AnalysisSessionImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  BootImageHeader
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBootImageHeader(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BootImageHeaderImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  CompressionFormat
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCompressionFormat(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CompressionFormatImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<ProgressUpdate> sse_decode_StreamSink_progress_update_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AnalysisSummary sse_decode_analysis_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kernelSize = sse_decode_usize(deserializer);
    var var_arch = sse_decode_String(deserializer);
    var var_kernelBase = sse_decode_u_64(deserializer);
    var var_symbolCount = sse_decode_usize(deserializer);
    return AnalysisSummary(
      kernelSize: var_kernelSize,
      arch: var_arch,
      kernelBase: var_kernelBase,
      symbolCount: var_symbolCount,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AnalysisSession
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
      deserializer,
    ));
  }

  @protected
  AnalysisSummary sse_decode_box_autoadd_analysis_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_analysis_summary(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  FrbKernelSymbol sse_decode_frb_kernel_symbol(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_addr = sse_decode_u_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_stype = sse_decode_String(deserializer);
    return FrbKernelSymbol(addr: var_addr, name: var_name, stype: var_stype);
  }

  @protected
  HexChunk sse_decode_hex_chunk(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_content = sse_decode_list_prim_u_8_strict(deserializer);
    var var_offset = sse_decode_u_64(deserializer);
    var var_totalSize = sse_decode_u_64(deserializer);
    return HexChunk(
      content: var_content,
      offset: var_offset,
      totalSize: var_totalSize,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<FrbKernelSymbol> sse_decode_list_frb_kernel_symbol(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FrbKernelSymbol>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_frb_kernel_symbol(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  AnalysisSession?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  AnalysisSummary? sse_decode_opt_box_autoadd_analysis_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_analysis_summary(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProgressUpdate sse_decode_progress_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_step = sse_decode_String(deserializer);
    var var_progress = sse_decode_f_32(deserializer);
    var var_summary = sse_decode_opt_box_autoadd_analysis_summary(deserializer);
    var var_session =
        sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
          deserializer,
        );
    return ProgressUpdate(
      step: var_step,
      progress: var_progress,
      summary: var_summary,
      session: var_session,
    );
  }

  @protected
  SortColumn sse_decode_sort_column(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SortColumn.values[inner];
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    AnalysisSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AnalysisSessionImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBootImageHeader(
    BootImageHeader self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BootImageHeaderImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCompressionFormat(
    CompressionFormat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CompressionFormatImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    AnalysisSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AnalysisSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    AnalysisSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AnalysisSessionImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    AnalysisSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as AnalysisSessionImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBootImageHeader(
    BootImageHeader self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BootImageHeaderImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerCompressionFormat(
    CompressionFormat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CompressionFormatImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_progress_update_Sse(
    RustStreamSink<ProgressUpdate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_progress_update,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_analysis_summary(
    AnalysisSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.kernelSize, serializer);
    sse_encode_String(self.arch, serializer);
    sse_encode_u_64(self.kernelBase, serializer);
    sse_encode_usize(self.symbolCount, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    AnalysisSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
      self,
      serializer,
    );
  }

  @protected
  void sse_encode_box_autoadd_analysis_summary(
    AnalysisSummary self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_analysis_summary(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_frb_kernel_symbol(
    FrbKernelSymbol self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.addr, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.stype, serializer);
  }

  @protected
  void sse_encode_hex_chunk(HexChunk self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.content, serializer);
    sse_encode_u_64(self.offset, serializer);
    sse_encode_u_64(self.totalSize, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_frb_kernel_symbol(
    List<FrbKernelSymbol> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_frb_kernel_symbol(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
    AnalysisSession? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_analysis_summary(
    AnalysisSummary? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_analysis_summary(self, serializer);
    }
  }

  @protected
  void sse_encode_progress_update(
    ProgressUpdate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.step, serializer);
    sse_encode_f_32(self.progress, serializer);
    sse_encode_opt_box_autoadd_analysis_summary(self.summary, serializer);
    sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnalysisSession(
      self.session,
      serializer,
    );
  }

  @protected
  void sse_encode_sort_column(SortColumn self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class AnalysisSessionImpl extends RustOpaque implements AnalysisSession {
  // Not to be used by end users
  AnalysisSessionImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  AnalysisSessionImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_AnalysisSession,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_AnalysisSession,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_AnalysisSessionPtr,
  );

  Uint8List get elfBytes => RustLib.instance.api
      .crateApiAnalysisSessionAutoAccessorGetElfBytes(that: this);

  AnalysisSummary get summary => RustLib.instance.api
      .crateApiAnalysisSessionAutoAccessorGetSummary(that: this);

  set elfBytes(Uint8List elfBytes) =>
      RustLib.instance.api.crateApiAnalysisSessionAutoAccessorSetElfBytes(
        that: this,
        elfBytes: elfBytes,
      );

  set summary(AnalysisSummary summary) =>
      RustLib.instance.api.crateApiAnalysisSessionAutoAccessorSetSummary(
        that: this,
        summary: summary,
      );

  /// Get the total count of symbols after filtering (for pagination).
  Future<BigInt> countFiltered({required String filter}) => RustLib.instance.api
      .crateApiAnalysisSessionCountFiltered(that: this, filter: filter);

  /// Read a chunk of the kernel for hex viewing.
  ///
  /// Alignment: This method aligns the offset and length to 16 bytes
  /// to simplify UI rendering (one row = 16 bytes).
  Future<HexChunk> getHexChunk({
    required BigInt offset,
    required BigInt length,
  }) => RustLib.instance.api.crateApiAnalysisSessionGetHexChunk(
    that: this,
    offset: offset,
    length: length,
  );

  /// Query symbols using server-side filtering and sorting.
  ///
  /// This is a "Zero-Copy" operation effectively, as we only return
  /// the small subset of data requested by the UI view.
  Future<List<FrbKernelSymbol>> querySymbols({
    required String filter,
    required SortColumn sortBy,
    required bool ascending,
    required BigInt page,
    required BigInt pageSize,
  }) => RustLib.instance.api.crateApiAnalysisSessionQuerySymbols(
    that: this,
    filter: filter,
    sortBy: sortBy,
    ascending: ascending,
    page: page,
    pageSize: pageSize,
  );
}

@sealed
class BootImageHeaderImpl extends RustOpaque implements BootImageHeader {
  // Not to be used by end users
  BootImageHeaderImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  BootImageHeaderImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_BootImageHeader,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_BootImageHeader,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_BootImageHeaderPtr,
  );
}

@sealed
class CompressionFormatImpl extends RustOpaque implements CompressionFormat {
  // Not to be used by end users
  CompressionFormatImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CompressionFormatImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_CompressionFormat,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_CompressionFormat,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_CompressionFormatPtr,
  );
}
